var message = "hello";
console.log(message);
var id = "1";
var email = "test@a.x";
var isActive = true;
var none;
none = "yes";
none = 1;
var memo;
console.log(typeof memo);
console.log(id, typeof id);
console.log(email, typeof email);
console.log(isActive, typeof isActive);
console.log(none, typeof none);
